build_prefix: extra-x86_64
maintainers:
- github: bshor
  email: boris@bshor.com
repo_depends:
- r-dplyr
- r-httr
- r-magrittr
- r-rappdirs
- r-sf
- r-stringr
- r-uuid
update_on:
- source: rpkgs
  pkgname: tigris
  repo: cran
  md5: true
- alias: r
