build_prefix: extra-x86_64
maintainers:
- github: starsareintherose
  email: kuoi@bioarchlinux.org
repo_depends:
- r-callr
- r-chromote
- r-magrittr
- r-promises
update_on:
- source: rpkgs
  pkgname: webshot2
  repo: cran
  md5: true
- alias: r
