build_prefix: extra-x86_64
maintainers:
- github: shun2wang
  email: shuonwang@gmail.com
repo_depends:
- r-checkmate
- r-rcpp
update_on:
- source: rpkgs
  pkgname: highs
  repo: cran
  md5: true
- alias: r
- source: alpm
  alpm: highs
  repo: extra
  strip_release: true
