build_prefix: extra-x86_64
maintainers:
- github: starsareintherose
  email: kuoi@bioarchlinux.org
repo_depends:
- r-cli
- r-curl
- r-deeptimedata
- r-ggfittext
- r-ggforce
- r-ggh4x
- r-ggplot2
- r-gridextra
- r-grimport2
- r-gtable
- r-lifecycle
- r-rlang
- r-scales
update_on:
- source: rpkgs
  pkgname: deeptime
  repo: cran
  md5: true
- alias: r
