maintainers:
- github: kashyapchhatbar
  email: kashyap.cc@gmail.com

pre_build_script: update_pkgver_and_pkgrel('7.7.1')

post_build: git_pkgbuild_commit

update_on:
- source: manual
  manual: 7.7.1 
- alias: python
