build_prefix: extra-x86_64
maintainers:
- email: sukanka@askk.cc
  github: sukanka
post_build_script: |
  git_pkgbuild_commit()
repo_depends:
- r-ggplot2
- r-orthopolynom
- r-partitions
- r-plyr
- r-polynom
- r-stringi
- r-stringr
- r-tidyr
update_on:
- regex: mpoly_([\d._-]+).tar.gz
  source: regex
  url: https://cran.r-project.org/package=mpoly
- alias: r
