build_prefix: extra-x86_64
maintainers:
- github: bshor
  email: boris@bshor.com
repo_depends:
- r-csppdata
- r-dplyr
- r-ggcorrplot
- r-ggplot2
- r-haven
- r-mapproj
- r-purrr
- r-readr
- r-rlang
- r-stringr
- r-tidyselect
update_on:
- source: rpkgs
  pkgname: cspp
  repo: cran
  md5: true
- alias: r
