build_prefix: extra-x86_64
maintainers:
- github: starsareintherose
  email: kuoi@bioarchlinux.org
repo_depends:
- r-cli
- r-farver
- r-glue
- r-labeling
- r-lifecycle
- r-r6
- r-rcolorbrewer
- r-rlang
- r-viridislite

update_on:
- source: rpkgs
  pkgname: scales
  repo: cran
  md5: true
- alias: r
