build_prefix: extra-x86_64
maintainers:
- github: starsareintherose
  email: kuoi@bioarchlinux.org
repo_depends:
- r-cli
- r-desc
- r-ellipsis
- r-fs
- r-lifecycle
- r-memoise
- r-miniui
- r-pak
- r-pkgbuild
- r-pkgdown
- r-pkgload
- r-profvis
- r-rcmdcheck
- r-rlang
- r-roxygen2
- r-rversions
- r-sessioninfo
- r-testthat
- r-urlchecker
- r-withr
- r-usethis
update_on:
- source: rpkgs
  pkgname: devtools
  repo: cran
  md5: true
- alias: r
