#!/bin/bash
rm -rf /home/bio/Packages/BioArchLinux/*/src
python /home/bio/Packages/BioArchLinux_CLEANER/lilac-cleaner -f
python /home/bio/Packages/BioArchLinux_CLEANER/repocleaner
chown -R bio:pkg /home/bio/Packages/BioArchLinux/*
