#!/bin/bash
for opt in "$@"
do
    case "$1" in
        --) shift ; break ;;
        -*) shift ;;
        *) break ;;
    esac
done

export FAKEROOTDONTTRYCHOWN=true
if [[ -n "${@}" ]]
then
  if [[ $FAKECHROOT == true ]]
  then
      fakechrootcmd=""
  else
      fakechrootcmd="fakechroot"
  fi

  if [[ -n $FAKED_MODE ]]
  then
      fakerootcmd=""
  else
      fakerootcmd="fakeroot"
  fi

  $fakechrootcmd $fakerootcmd "${@}"
fi
