build_prefix: extra-x86_64
maintainers:
- github: pekkarr
  email: pekkarr@protonmail.com
repo_depends:
- r-cellranger
- r-cpp11
- r-minty
- r-stringi
- r-tibble
- r-vctrs
- r-withr
- r-zip
repo_makedepends:
- r-knitr
- r-readr
- r-testthat
update_on:
- source: rpkgs
  pkgname: readODS
  repo: cran
  md5: true
- alias: r
